services:
  - type: web
    name: product-web-api
    plan: free
    docker:
      dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1