spring:
  application:
    name: product-web-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # ← HARDCODE this
        format_sql: true
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://dpg-d3fn6bp5pdvs73be51ag-a.oregon-postgres.render.com:5432/roth # ← HARDCODE your URL
    username: roth_user # ← HARDCODE username
    password: ArTlnsMDelJMYbabV93WhrQI6ag5rZUL # ← HARDCODE password
    driver-class-name: org.postgresql.Driver # ← HARDCODE driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

server:
  port: 10000 # ← HARDCODE port for Render
  error:
    include-message: always

file:
  upload-dir: ./uploads

logging:
  level:
    com.setec: INFO
    org.hibernate.SQL: WARN
